## APPLICATION CUSTOM CONFIG
app:
  masterDB:
    host: 192.168.9.105:33060
    name: db_seckill_monolithic
    username: seckill_app
    password: secki1105@mysql.COM
  dataSource:
    master:
      name: MasterSource
      type: com.alibaba.druid.pool.DruidDataSource
      driverClass: com.mysql.jdbc.Driver
      url: jdbc:mysql://${app.masterDB.host}/${app.masterDB.name}?useSSL=false&autoReconnect=true&useOldAliasMetadataBehavior=true
      username: ${app.masterDB.username}
      password: ${app.masterDB.password}
      filters: stat,wall,slf4j
      connectionProperties: druid.log.stmt.executableSql=true;druid.stat.logSlowSql=true;

## EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  address: 127.0.0.1 # Network address to which the server should bind to.
  port: 8888 # Server HTTP port.
  compression:
    enabled: true # If response compression is enabled.
    mime-types: text/html,text/xml,text/css,application/json,application/xml # Comma-separated list of MIME types that should be compressed. For instance `text/html,text/css,application/json`
    min-response-size: 1024 # Minimum response size that is required for compression to be performed. For instance 2048
  session-timeout: 3600 # Session timeout in seconds.
  tomcat:
    uri-encoding: UTF-8

## LOGGING
logging:
  path: D:/LOGFILE/xq_seckill_monolithic
  config: classpath:config/logback.xml
  #OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
  level:
    application : WARN
    druid.sql: DEBUG
    #druid.sql.DataSource: DEBUG
    #druid.sql.Connection: DEBUG
    #druid.sql.Statement: DEBUG
    #druid.sql.ResultSet: DEBUG
    net.lovexq.seckill: DEBUG
    org.apache.activemq: WARN
    org.apache.http: WARN
    org.hibernate: WARN
    org.springframework: WARN
    org.springframework.boot: INFO
    org.thymeleaf: WARN

## SPRING CONFIGURATION
spring:
  ## ACTIVEMQ
  activemq:
    broker-url: failover:(tcp://127.0.0.1:61616)
    user: mquser
    password: mqpwd
  devtools:
    restart:
      enabled: true
  ## DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#  datasource:
#      name: MasterSource
#      type: com.alibaba.druid.pool.DruidDataSource
#      driverClass: com.mysql.jdbc.Driver
#      url: jdbc:mysql://${app.masterDB.host}/${app.masterDB.name}?useSSL=false&autoReconnect=true&useOldAliasMetadataBehavior=true
#      username: ${app.masterDB.username}
#      password: ${app.masterDB.password}
  ## JPA CONFIGURATION
#  jpa:
#    show-sql: true
#    generate-ddl: false # ignored by Hibernate, might be useful for other vendors
#    hibernate:
#      ddl-auto: update # defaults to create-drop for embedded dbs
  ## THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    cache: false # Enable template caching.
    check-template: true # Check that the template exists before rendering it.
    check-template-location: true # Check that the templates location exists.
    content-type: text/html # Content-Type value.
    enabled: true # Enable MVC Thymeleaf view resolution.
    encoding: UTF-8 # Template encoding.
    mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.