## APPLICATION CUSTOM CONFIG
app:
  ## Relational Databases
  dataSource:
    master:
      name: master
      driverClass: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.9.105:33060/db_seckill_monolithic?useSSL=false&autoReconnect=true&useOldAliasMetadataBehavior=true
      username: 
      password: 
    slaves:
      slave1:
        name: slave1
        driverClass: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.9.105:33060/db_seckill_monolithic?useSSL=false&autoReconnect=true&useOldAliasMetadataBehavior=true
        username: 
        password: 
      slave2:
        name: slave2
        driverClass: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.9.106:33060/db_seckill_monolithic?useSSL=false&autoReconnect=true&useOldAliasMetadataBehavior=true
        username: 
        password: 

  liaJiaCookie:

## Druid
druid:
  initialSize: 8
  minIdle: 8
  maxActive: 64
  validationQuery: "SELECT 1 FROM DUAL"
  removeAbandoned: true
  removeAbandonedTimeout: 1800
  logAbandoned: 1800

## LOGGING
logging:
  path: D:/LOGFILE/xq_seckill_monolithic
  config: classpath:config/logback.xml
  #OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
  level:
    application : DEBUG
    druid.sql: DEBUG
    net.lovexq.seckill: DEBUG
    org.apache.activemq: WARN
    org.apache.http: WARN
    org.hibernate: WARN
    org.springframework: WARN
    org.springframework.boot: WARN
    org.springframework.cache: WARN
    org.springframework.data: WARN
    org.thymeleaf: WARN

## EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  address: 127.0.0.1 # Network address to which the server should bind to.
  port: 8888 # Server HTTP port.
  compression:
    enabled: true # If response compression is enabled.
    mime-types: text/html,text/xml,text/css,application/json,application/xml # Comma-separated list of MIME types that should be compressed. For instance `text/html,text/css,application/json`
    min-response-size: 1024 # Minimum response size that is required for compression to be performed. For instance 2048
  session-timeout: 3600 # Session timeout in seconds.
  tomcat:
    uri-encoding: UTF-8

## SPRING CONFIGURATION
spring:
  ## ACTIVEMQ
  activemq:
    broker-url: failover:(tcp://192.168.9.101:62626)
    user: mquser
    password: mqpwd
  ## devtools
  devtools:
    restart:
      enabled: true
  ## THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    cache: false # Enable template caching.
    check-template: true # Check that the template exists before rendering it.
    check-template-location: true # Check that the templates location exists.
    content-type: text/html # Content-Type value.
    enabled: true # Enable MVC Thymeleaf view resolution.
    encoding: UTF-8 # Template encoding.
    mode: HTML # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.
  ## REDIS (RedisProperties)
  redis:
    host: 192.168.9.102
    port: 16379
    password:
    database: 1
    pool:
      minIdle: 8
      maxIdle: 64
      maxActive: 128
      maxWait: 60000
    timeout: 10000